
package com.graduacao.roteiro04.gui.dialogs;


import com.graduacao.roteiro04.classes.Consulta;
import com.graduacao.roteiro04.classes.Medico;
import com.graduacao.roteiro04.classes.Paciente;
import com.graduacao.roteiro04.gui.FrHome;

import javax.swing.JOptionPane;

public class DlgConsulta extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgConsulta.class.getName());
    private FrHome pai;
    private Consulta consulta;
    private boolean pronto;
    
    public DlgConsulta(java.awt.Frame parent, boolean modal, Consulta consulta, boolean editar) {
        super(parent, modal);
        initComponents();
        this.pronto = false;
        this.pai = (FrHome) parent;
        this.consulta = consulta;
        
        
        this.edtCodigo.setEnabled(!editar);
        this.atualizarConsulta();
        this.objetoParaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtDisciplina = new javax.swing.JTextArea();
        panConfirmar = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        panCampos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        edtData = new javax.swing.JTextField();
        lblHora = new javax.swing.JLabel();
        edtHora = new javax.swing.JTextField();
        btnMedico = new javax.swing.JButton();
        btnPaciente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("Consulta");

        edtDisciplina.setEditable(false);
        edtDisciplina.setColumns(20);
        edtDisciplina.setRows(5);
        jScrollPane1.setViewportView(edtDisciplina);

        panConfirmar.setBackground(new java.awt.Color(204, 204, 204));
        panConfirmar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panConfirmar.add(btnCancelar);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);
        panConfirmar.add(btnSalvar);

        panCampos.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Código: ");

        lblData.setText("Data: ");

        lblHora.setText("Hora: ");

        edtHora.setToolTipText("");

        btnMedico.setText("Escolher Médico");
        btnMedico.addActionListener(this::btnMedicoActionPerformed);

        btnPaciente.setText("Escolher Paciente");
        btnPaciente.addActionListener(this::btnPacienteActionPerformed);

        javax.swing.GroupLayout panCamposLayout = new javax.swing.GroupLayout(panCampos);
        panCampos.setLayout(panCamposLayout);
        panCamposLayout.setHorizontalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtHora)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtData, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panCamposLayout.setVerticalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData)
                    .addComponent(edtData, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHora)
                    .addComponent(edtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaciente))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicoActionPerformed
        DlgEscolhaMedico escolha = new DlgEscolhaMedico(this.pai,true,this.pai.getGerenteMedicos());
        escolha.setLocation(this.getLocation());
        escolha.setVisible(true);
        
        Medico medico = escolha.getMedicoEscolhido();
        if(medico != null){
            this.consulta.setMedico(medico);
            this.atualizarConsulta();
        }
    }//GEN-LAST:event_btnMedicoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(!this.edtCodigo.getText().isBlank() && !this.consulta.getMedico().getCrm().isBlank() && !this.consulta.getPaciente().getCpf().isBlank()){
            this.camposParaObjeto();
            this.pronto = true;
            this.dispose();
        }
        else if (this.edtCodigo.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Preencha o código!");
        }
        else if(this.consulta.getMedico().getCrm().isBlank()){
            JOptionPane.showMessageDialog(this, "Escolha um Médico!");
        }
        else{
            JOptionPane.showMessageDialog(this, "Escolha um Paciente!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        DlgEscolhaPaciente escolha = new DlgEscolhaPaciente(this.pai,true,this.pai.getGerentePacientes());
        escolha.setLocation(this.getLocation());
        escolha.setVisible(true);
        
        Paciente paciente = escolha.getPacienteEscolhido();
        if(paciente != null){
            this.consulta.setPaciente(paciente);
            this.atualizarConsulta();
        }
    }//GEN-LAST:event_btnPacienteActionPerformed

    public void camposParaObjeto(){
        this.consulta.setCod(this.edtCodigo.getText());
        this.consulta.setData(this.edtData.getText());
        this.consulta.setHora(this.edtHora.getText());
    }
    
    public void objetoParaCampos(){
        this.edtCodigo.setText(this.consulta.getCod());
        this.edtData.setText(this.consulta.getData());
        this.edtHora.setText(this.consulta.getHora());
    }
    
    public boolean isPronto() {
        return this.pronto;
    }

    public void atualizarConsulta(){
        this.edtDisciplina.setText(this.consulta.getMedico().toString() + this.consulta.getPaciente().toString());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnMedico;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtData;
    private javax.swing.JTextArea edtDisciplina;
    private javax.swing.JTextField edtHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel panCampos;
    private javax.swing.JPanel panConfirmar;
    // End of variables declaration//GEN-END:variables
}
