package com.graduacao.roteiro04.gui.dialogs;


import com.graduacao.roteiro04.classes.Paciente;
import com.graduacao.roteiro04.gerentes.GerentePaciente;
import com.graduacao.roteiro04.gui.FrHome;
import javax.swing.JOptionPane;

public class DlgCadPaciente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgCadPaciente.class.getName());
    
    private FrHome pai;
    private final GerentePaciente gerente;
    private boolean editando;
    private String pathFile;
    public DlgCadPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        this.pai = (FrHome) parent;
        this.gerente = this.pai.getGerentePacientes();
        this.pathFile = this.pai.getPathFilePaciente();
        this.edtListagem.setText(this.gerente.toString());
        this.habilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        panCampos = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        edtCpf = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        edtDataNascimento = new javax.swing.JTextField();
        lblHistorico = new javax.swing.JLabel();
        edtHistorico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Pacientes");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        panBotoes.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        panBotoes.add(btnEditar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panBotoes.add(btnCancelar);

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);
        panBotoes.add(btnExcluir);

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);
        panBotoes.add(btnSalvar);

        panCampos.setBackground(new java.awt.Color(204, 204, 204));

        lblCpf.setText("CPF: ");

        edtCpf.setEnabled(false);

        lblNome.setText("Nome: ");

        edtNome.setEnabled(false);

        lblDataNascimento.setText("Data de Nascimento");

        edtDataNascimento.setEnabled(false);

        lblHistorico.setText("Histórico Médico: ");

        edtHistorico.setEnabled(false);

        javax.swing.GroupLayout panCamposLayout = new javax.swing.GroupLayout(panCampos);
        panCampos.setLayout(panCamposLayout);
        panCamposLayout.setHorizontalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNome)
                        .addGap(6, 6, 6)
                        .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblDataNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHistorico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        panCamposLayout.setVerticalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCpf)
                    .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataNascimento)
                    .addComponent(edtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHistorico)
                        .addComponent(edtHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        edtListagem.setEditable(false);
        edtListagem.setColumns(20);
        edtListagem.setRows(5);
        jScrollPane1.setViewportView(edtListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.editando = false;
        this.limparCampos();
        this.habilitarCampos(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        DlgEscolhaPaciente escolha = new DlgEscolhaPaciente(this.pai,true,this.gerente);
        escolha.setLocation(this.getLocation());
        escolha.setVisible(true);
        
        Paciente paciente = escolha.getPacienteEscolhido();
        if(paciente != null){
            this.limparCampos();
            this.editando = true;
            this.habilitarCampos(true);
            this.objetoParaCampos(paciente);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        DlgEscolhaPaciente escolha = new DlgEscolhaPaciente(this.pai,true,this.gerente);
        escolha.setLocation(this.getLocation());
        escolha.setVisible(true);
        
        Paciente paciente = escolha.getPacienteEscolhido();
        if(paciente != null){
            this.gerente.remove(paciente.getCpf());
            JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso!");
        }
        this.habilitarCampos(false);
        this.edtListagem.setText(this.gerente.toString());
        this.gerente.salvarNoArquivo(pathFile);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(this.edtCpf.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Preencha o CPF!");   
        }else{
            Paciente paciente = this.camposParaObjeto();

            if(editando || !this.gerente.containsKey(paciente.getCpf())){
                this.gerente.put(paciente);
            }
            else{
                JOptionPane.showMessageDialog(this, "Já existe um Paciente com este CPF!");
            }
            this.limparCampos();
            this.habilitarCampos(false);
            this.gerente.salvarNoArquivo(this.pathFile);
            this.edtListagem.setText(this.gerente.toString());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    public void habilitarCampos(boolean flag){
        this.edtCpf.setEnabled(!this.editando && flag);
        this.edtNome.setEnabled(flag);
        this.edtDataNascimento.setEnabled(flag);
        this.edtHistorico.setEnabled(flag);
        
        this.habilitarBotoes(flag);
    }
    public void habilitarBotoes(boolean flag){
        this.btnNovo.setEnabled(!flag);
        this.btnEditar.setEnabled(this.gerente.size() > 0 && !flag);
        this.btnCancelar.setEnabled(flag);
        this.btnExcluir.setEnabled(this.gerente.size() > 0 && !flag);
        this.btnSalvar.setEnabled(flag);
    }
    public void limparCampos(){
        this.edtCpf.setText("");
        this.edtNome.setText("");
        this.edtDataNascimento.setText("");
        this.edtHistorico.setText("");
    }
    
    public void objetoParaCampos(Paciente paciente){
        this.edtCpf.setText(paciente.getCpf());
        this.edtNome.setText(paciente.getNome());
        this.edtDataNascimento.setText(paciente.getDataNascimento());
        this.edtHistorico.setText(paciente.getHistorico());
    }
    public Paciente camposParaObjeto(){
        Paciente paciente = new Paciente();
        paciente.setCpf(this.edtCpf.getText());
        paciente.setNome(this.edtNome.getText());
        paciente.setDataNascimento(this.edtDataNascimento.getText());
        paciente.setHistorico(this.edtHistorico.getText());
        
       return paciente;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtCpf;
    private javax.swing.JTextField edtDataNascimento;
    private javax.swing.JTextField edtHistorico;
    private javax.swing.JTextArea edtListagem;
    private javax.swing.JTextField edtNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblHistorico;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panBotoes;
    private javax.swing.JPanel panCampos;
    // End of variables declaration//GEN-END:variables
}
