package com.graduacao.roteiro04.gui.dialogs;


import com.graduacao.roteiro04.classes.Medico;
import com.graduacao.roteiro04.gerentes.GerenteMedico;
import com.graduacao.roteiro04.gui.FrHome;
import javax.swing.JOptionPane;

public class DlgCadMedico extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgCadMedico.class.getName());
    
    private FrHome pai;
    private final GerenteMedico gerente;
    private boolean editando;
    private String pathFile;
    public DlgCadMedico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        this.pai = (FrHome) parent;
        this.gerente = this.pai.getGerenteMedicos();
        this.pathFile = this.pai.getPathFileMedico();
        this.edtListagem.setText(this.gerente.toString());
        this.habilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        panCampos = new javax.swing.JPanel();
        lblCrm = new javax.swing.JLabel();
        edtCrm = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblEspecialidade = new javax.swing.JLabel();
        edtEspecialidade = new javax.swing.JTextField();
        lblHorarios = new javax.swing.JLabel();
        edtHorarios = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Médicos");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        panBotoes.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        panBotoes.add(btnEditar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panBotoes.add(btnCancelar);

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);
        panBotoes.add(btnExcluir);

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);
        panBotoes.add(btnSalvar);

        panCampos.setBackground(new java.awt.Color(204, 204, 204));

        lblCrm.setText("CRM: ");

        edtCrm.setEnabled(false);

        lblNome.setText("Nome: ");

        edtNome.setEnabled(false);

        lblEspecialidade.setText("Especialidade: ");

        edtEspecialidade.setEnabled(false);

        lblHorarios.setText("Horários Dísponiveis: ");

        edtHorarios.setEnabled(false);

        javax.swing.GroupLayout panCamposLayout = new javax.swing.GroupLayout(panCampos);
        panCampos.setLayout(panCamposLayout);
        panCamposLayout.setHorizontalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblCrm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCrm, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblEspecialidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblHorarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtHorarios))
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(6, 6, 6)
                        .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panCamposLayout.setVerticalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCrm)
                    .addComponent(edtCrm, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEspecialidade)
                    .addComponent(edtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHorarios)
                        .addComponent(edtHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        edtListagem.setEditable(false);
        edtListagem.setColumns(20);
        edtListagem.setRows(5);
        jScrollPane1.setViewportView(edtListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.editando = false;
        this.limparCampos();
        this.habilitarCampos(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        DlgEscolhaMedico escolha = new DlgEscolhaMedico(this.pai,true,this.gerente);
        escolha.setLocation(this.getLocation());
        escolha.setVisible(true);
        
        Medico medico = escolha.getMedicoEscolhido();
        if(medico != null){
            this.limparCampos();
            this.editando = true;
            this.habilitarCampos(true);
            this.objetoParaCampos(medico);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        DlgEscolhaMedico escolha = new DlgEscolhaMedico(this.pai,true,this.gerente);
        escolha.setLocation(this.getLocation());
        escolha.setVisible(true);
        
        Medico medico = escolha.getMedicoEscolhido();
        if(medico != null){
            this.gerente.remove(medico.getCrm());
            JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso!");
        }
        this.habilitarCampos(false);
        this.edtListagem.setText(this.gerente.toString());
        this.gerente.salvarNoArquivo(pathFile);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(this.edtCrm.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Preencha o CRM!");   
        }else{
            Medico medico = this.camposParaObjeto();

            if(editando || !this.gerente.containsKey(medico.getCrm())){
                this.gerente.put(medico);
            }
            else{
                JOptionPane.showMessageDialog(this, "Já existe um Médico com este CRM!");
            }
            this.limparCampos();
            this.habilitarCampos(false);
            this.gerente.salvarNoArquivo(this.pathFile);
            this.edtListagem.setText(this.gerente.toString());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    public void habilitarCampos(boolean flag){
        this.edtCrm.setEnabled(!this.editando && flag);
        this.edtNome.setEnabled(flag);
        this.edtEspecialidade.setEnabled(flag);
        this.edtHorarios.setEnabled(flag);
        
        this.habilitarBotoes(flag);
    }
    public void habilitarBotoes(boolean flag){
        this.btnNovo.setEnabled(!flag);
        this.btnEditar.setEnabled(this.gerente.size() > 0 && !flag);
        this.btnCancelar.setEnabled(flag);
        this.btnExcluir.setEnabled(this.gerente.size() > 0 && !flag);
        this.btnSalvar.setEnabled(flag);
    }
    public void limparCampos(){
        this.edtCrm.setText("");
        this.edtNome.setText("");
        this.edtEspecialidade.setText("");
        this.edtHorarios.setText("");
    }
    
    public void objetoParaCampos(Medico medico){
        this.edtCrm.setText(medico.getCrm());
        this.edtNome.setText(medico.getNome());
        this.edtEspecialidade.setText(medico.getEspecialidade());
        this.edtHorarios.setText(medico.getAgendaDisponivel());
    }
    public Medico camposParaObjeto(){
        Medico medico = new Medico();
        medico.setCrm(this.edtCrm.getText());
        medico.setNome(this.edtNome.getText());
        medico.setEspecialidade(this.edtEspecialidade.getText());
        medico.setAgendaDisponivel(this.edtHorarios.getText());
        
       return medico;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtCrm;
    private javax.swing.JTextField edtEspecialidade;
    private javax.swing.JTextField edtHorarios;
    private javax.swing.JTextArea edtListagem;
    private javax.swing.JTextField edtNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCrm;
    private javax.swing.JLabel lblEspecialidade;
    private javax.swing.JLabel lblHorarios;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panBotoes;
    private javax.swing.JPanel panCampos;
    // End of variables declaration//GEN-END:variables
}
