package com.graduacao.roteiro04.gui.dialogs;

import com.graduacao.roteiro04.classes.Consulta;
import com.graduacao.roteiro04.gerentes.GerenteConsulta;
import com.graduacao.roteiro04.gui.FrHome;
import javax.swing.JOptionPane;

public class DlgCadConsulta extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgCadConsulta.class.getName());
    private GerenteConsulta gerente;
    private FrHome pai;
    private String pathFile;
    public DlgCadConsulta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.pai = (FrHome) parent;
        this.gerente = this.pai.getGerenteConsultas();
        this.pathFile = this.pai.getPathFileConsulta();
        this.edtListagem.setText(this.gerente.toStringResumido());
        this.habilitarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Consultas");

        panBotoes.setBackground(new java.awt.Color(204, 204, 204));

        btnNovo.setText("Nova");
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        panBotoes.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        panBotoes.add(btnEditar);

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);
        panBotoes.add(btnExcluir);

        edtListagem.setEditable(false);
        edtListagem.setColumns(20);
        edtListagem.setRows(5);
        jScrollPane1.setViewportView(edtListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addComponent(panBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        Consulta consulta = new Consulta();
        
        DlgConsulta criaConsulta = new DlgConsulta(this.pai, true, consulta, false);
        criaConsulta.setLocation(this.getLocation());
        criaConsulta.setVisible(true);
        
        if(criaConsulta.isPronto()){
            if(!this.gerente.containsKey(consulta.getCod())){
                this.gerente.put(consulta);
                this.gerente.salvarNoArquivo(pathFile);
                this.atualizarListagem();
                this.habilitarBotoes();
            }
            else{
                JOptionPane.showMessageDialog(this, "Já existe uma consulta com este código!");
            }
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        DlgEscolhaConsulta escolha = new DlgEscolhaConsulta(this.pai,true,this.gerente);
        escolha.setLocation(this.getLocation());
        escolha.setVisible(true);
        
        Consulta consulta = escolha.getConsultaEscolhida();
        if(consulta != null){
            DlgConsulta editaConsulta = new DlgConsulta(this.pai, true, consulta, true);
            editaConsulta.setLocation(this.getLocation());
            editaConsulta.setVisible(true);

            if(editaConsulta.isPronto()){
                this.gerente.put(consulta);
                this.gerente.salvarNoArquivo(pathFile);
                this.atualizarListagem();
                this.habilitarBotoes();
            }   
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        DlgEscolhaConsulta escolha = new DlgEscolhaConsulta(this.pai,true,this.gerente);
        escolha.setLocation(this.getLocation());
        escolha.setVisible(true);
        
        Consulta consulta = escolha.getConsultaEscolhida();
        if(consulta != null){
            this.gerente.remove(consulta.getCod());
            this.gerente.salvarNoArquivo(pathFile);
            this.atualizarListagem();
            JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso!");
            this.habilitarBotoes();

        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    public void habilitarBotoes(){
        this.btnEditar.setEnabled(this.gerente.size() > 0);
        this.btnExcluir.setEnabled(this.gerente.size() > 0);
    }
    
    public void atualizarListagem(){
        this.edtListagem.setText(this.gerente.toStringResumido());
    }
    
    
    


  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JTextArea edtListagem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panBotoes;
    // End of variables declaration//GEN-END:variables
}
