package com.graduacao.exercicios_3_6.gui;

public class FrExercicios_3_6 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrExercicios_3_6.class.getName());
    
    public static FrExercicios_3_6 tela;
    
    
    public FrExercicios_3_6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panBotoes = new javax.swing.JPanel();
        btnExercicio01 = new javax.swing.JButton();
        btnExercicio03 = new javax.swing.JButton();
        btnExercicio02 = new javax.swing.JButton();
        btnExercicio04 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Exercícios 3.6");

        panBotoes.setBackground(new java.awt.Color(204, 204, 204));

        btnExercicio01.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExercicio01.setText("Exercício01");
        btnExercicio01.addActionListener(this::btnExercicio01ActionPerformed);

        btnExercicio03.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExercicio03.setText("Exercício03");
        btnExercicio03.setEnabled(false);
        btnExercicio03.addActionListener(this::btnExercicio03ActionPerformed);

        btnExercicio02.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExercicio02.setText("Exercício02");
        btnExercicio02.setEnabled(false);

        btnExercicio04.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExercicio04.setText("Exercício04");
        btnExercicio04.setEnabled(false);

        javax.swing.GroupLayout panBotoesLayout = new javax.swing.GroupLayout(panBotoes);
        panBotoes.setLayout(panBotoesLayout);
        panBotoesLayout.setHorizontalGroup(
            panBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExercicio04, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panBotoesLayout.createSequentialGroup()
                        .addComponent(btnExercicio01, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExercicio02, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnExercicio03, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panBotoesLayout.setVerticalGroup(
            panBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExercicio01, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExercicio03, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExercicio02, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnExercicio04, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExercicio03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExercicio03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExercicio03ActionPerformed

    private void btnExercicio01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExercicio01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExercicio01ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExercicio01;
    private javax.swing.JButton btnExercicio02;
    private javax.swing.JButton btnExercicio03;
    private javax.swing.JButton btnExercicio04;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panBotoes;
    // End of variables declaration//GEN-END:variables
}
