CREATE TABLE ALUNO (CPF_ALU INTEGER,
NOME_ALU VARCHAR (40), 
LOG_END_ALU VARCHAR (40),
NUM_END_ALU VARCHAR (10),
BAI_END_ALU VARCHAR (30),
CID_END_ALU VARCHAR (40),
UF_END_ALU VARCHAR (2) )

ALTER TABLE ALUNO ADD PRIMARY KEY (CPF_ALU)

ALTER TABLE ALUNO ADD COD_DEPTO INTEGER

CREATE TABLE DEPARTAMENTO (COD_DEPTO INTEGER PRIMARY KEY ,
NOME_DEPTO VARCHAR(30) NOT NULL)

ALTER TABLE ALUNO ADD FOREIGN KEY (COD_DEPTO)
REFERENCES DEPARTAMENTO (COD_DEPTO)

DROP TABLE ALUNO

CREATE TABLE ALUNO (CPF_ALU INTEGER PRIMARY KEY,
NOME_ALU VARCHAR (40) NOT NULL, 
LOG_END_ALU VARCHAR (40) NOT NULL,
NUM_END_ALU VARCHAR (10) NOT NULL,
BAI_END_ALU VARCHAR (30) NOT NULL,
CID_END_ALU VARCHAR (40) NOT NULL, 
UF_END_ALU VARCHAR (2) NOT NULL,
COD_DEPTO INTEGER NOT NULL)

ALTER TABLE ALUNO ADD FOREIGN KEY (COD_DEPTO)
REFERENCES DEPARTAMENTO (COD_DEPTO)


CREATE TABLE CLIENTE (COD_CLI INTEGER PRIMARY KEY,
NOME_CLI VARCHAR (40) NOT NULL,
END_CLI VARCHAR (40) NOT NULL,
CID_CLI VARCHAR(30) NOT NULL,
UF_CLI VARCHAR(2) NOT NULL
)
CREATE TABLE PEDIDOS (COD_PED INTEGER PRIMARY KEY,
DATA_PED DATE NOT NULL,
COD_CLI INTEGER NOT NULL)

ALTER TABLE PEDIDOS ADD FOREIGN KEY (COD_CLI)
REFERENCES CLIENTE (COD_CLI)









