/*Exercícios de SELECT*/
/*01*/
SELECT COD_CLIENTE, NOME_CLIENTE FROM CLIENTE;
/*02*/
SELECT * FROM VENDEDOR WHERE SALARIO_FIXO > 3000.00;
/*03*/
SELECT DESCRICAO_PRODUTO, VALOR_UNITARIO FROM PRODUTO;
/*04*/
SELECT NUM_PEDIDO, PRAZO_ENTREGA_PEDIDO FROM PEDIDO;
/*05*/
SELECT NUM_PEDIDO, NOME_VENDEDOR FROM PEDIDO 
JOIN VENDEDOR ON VENDEDOR.COD_VENDEDOR = PEDIDO.COD_VENDEDOR;
/*06*/
SELECT NUM_PEDIDO, NOME_VENDEDOR, PRAZO_ENTREGA_PEDIDO FROM PEDIDO 
JOIN VENDEDOR ON VENDEDOR.COD_VENDEDOR = PEDIDO.COD_VENDEDOR;
/*07*/
SELECT * FROM PRODUTO WHERE VALOR_UNITARIO > 100;
/*08*/
SELECT NOME_CLIENTE FROM CLIENTE WHERE UF_CLIENTE = 'MG';
/*09*/
SELECT NUM_PEDIDO, PRAZO_ENTREGA_PEDIDO, PEDIDO.COD_CLIENTE, PEDIDO.COD_VENDEDOR, NOME_CLIENTE, NOME_VENDEDOR FROM PEDIDO 
JOIN VENDEDOR ON VENDEDOR.COD_VENDEDOR = PEDIDO.COD_VENDEDOR
JOIN CLIENTE ON CLIENTE.COD_CLIENTE = PEDIDO.COD_CLIENTE;
/*10*/
SELECT * FROM ITEM_PEDIDO;
/*11*/
SELECT NUM_PEDIDO, DESCRICAO_PRODUTO, QUANT_PEDIDA FROM ITEM_PEDIDO
JOIN PRODUTO ON PRODUTO.NUM_PRODUTO = ITEM_PEDIDO.NUM_PRODUTO;
/*12*/
SELECT * FROM CLIENTE C
WHERE C.COD_CLIENTE != ALL(SELECT COD_CLIENTE FROM PEDIDO);
/*13*/
SELECT * FROM VENDEDOR V
WHERE V.COD_VENDEDOR != ALL(SELECT COD_VENDEDOR FROM PEDIDO);
/*14*/
SELECT * FROM PRODUTO P
WHERE P.NUM_PRODUTO != ALL(SELECT NUM_PRODUTO FROM ITEM_PEDIDO);
/*15*/
SELECT NOME_CLIENTE, COUNT(NUM_PEDIDO) FROM CLIENTE C, PEDIDO P
WHERE C.COD_CLIENTE = P.COD_CLIENTE
GROUP BY NOME_CLIENTE;
/*16*/
SELECT NUM_PRODUTO, SUM(QUANT_PEDIDA) FROM ITEM_PEDIDO
GROUP BY NUM_PRODUTO;
/*17*/
SELECT AVG(VALOR_UNITARIO) FROM PRODUTO;
/*18*/
SELECT MAX(VALOR_UNITARIO), MIN(VALOR_UNITARIO)  FROM PRODUTO;
/*19*/
SELECT NOME_VENDEDOR, COUNT(NUM_PEDIDO) FROM VENDEDOR V, PEDIDO P
WHERE V.COD_VENDEDOR = P.COD_VENDEDOR
GROUP BY NOME_VENDEDOR;
/*20*/
SELECT * FROM CLIENTE
ORDER BY NOME_CLIENTE;
/*21*/
SELECT * FROM PRODUTO
ORDER BY VALOR_UNITARIO DESC;
/*22*/
SELECT * FROM PEDIDO WHERE PRAZO_ENTREGA_PEDIDO < 15;
/*23*/
SELECT NOME_CLIENTE, CID_CLIENTE FROM CLIENTE;
/*24*/
SELECT NUM_PEDIDO, SUM(QUANT_PEDIDA) FROM ITEM_PEDIDO
GROUP BY NUM_PEDIDO
ORDER BY NUM_PEDIDO ASC;
/*25*/
SELECT I.NUM_PEDIDO, P.NUM_PRODUTO, I.QUANT_PEDIDA, P.VALOR_UNITARIO, (I.QUANT_PEDIDA*P.VALOR_UNITARIO) AS TOTAL FROM ITEM_PEDIDO I, PRODUTO P
WHERE P.NUM_PRODUTO = I.NUM_PRODUTO
ORDER BY NUM_PEDIDO ASC;
/*26*/
SELECT I.NUM_PEDIDO, SUM(I.QUANT_PEDIDA*P.VALOR_UNITARIO) AS TOTAL FROM ITEM_PEDIDO I, PRODUTO P
WHERE P.NUM_PRODUTO = I.NUM_PRODUTO
GROUP BY I.NUM_PEDIDO
ORDER BY NUM_PEDIDO ASC;
/*27*/
SELECT V.COD_VENDEDOR, SUM(I.QUANT_PEDIDA*P.VALOR_UNITARIO) AS TOTAL FROM ITEM_PEDIDO I, PRODUTO P, VENDEDOR V, PEDIDO PE
WHERE P.NUM_PRODUTO = I.NUM_PRODUTO AND PE.NUM_PEDIDO = I.NUM_PEDIDO AND V.COD_VENDEDOR = PE.COD_VENDEDOR
GROUP BY V.COD_VENDEDOR
ORDER BY V.COD_VENDEDOR ASC;
/*28*/
SELECT C.NOME_CLIENTE, COUNT(P.COD_CLIENTE) FROM CLIENTE C, PEDIDO P
WHERE C.COD_CLIENTE = P.COD_CLIENTE
GROUP BY NOME_CLIENTE
HAVING COUNT(P.COD_CLIENTE) > 3;
/*29*/
SELECT NUM_PRODUTO, SUM(QUANT_PEDIDA) FROM ITEM_PEDIDO
GROUP BY NUM_PRODUTO
HAVING SUM(QUANT_PEDIDA) > 100
ORDER BY NUM_PRODUTO ASC;
/*30*/
SELECT C.NOME_CLIENTE, PE.NUM_PEDIDO, P.DESCRICAO_PRODUTO, I.QUANT_PEDIDA, P.VALOR_UNITARIO, (P.VALOR_UNITARIO * I.QUANT_PEDIDA) AS TOTAL
FROM CLIENTE C, PEDIDO PE, ITEM_PEDIDO I, PRODUTO P
WHERE C.COD_CLIENTE = PE.COD_CLIENTE AND PE.NUM_PEDIDO = I.NUM_PEDIDO AND I.NUM_PRODUTO = P.NUM_PRODUTO;
/*31*/
SELECT * FROM PRODUTO
WHERE VALOR_UNITARIO BETWEEN 50.00 AND 200.00; 
/*32*/
SELECT * FROM VENDEDOR
WHERE SALARIO_FIXO BETWEEN 2000.00 AND 5000.00;
/*33*/
SELECT * FROM PEDIDO
WHERE PRAZO_ENTREGA_PEDIDO BETWEEN 5 AND 20;
/*34*/
SELECT * FROM CLIENTE
WHERE COD_CLIENTE BETWEEN 100 AND 200;
/*35*/
SELECT * FROM ITEM_PEDIDO
WHERE QUANT_PEDIDA BETWEEN 10 AND 50;
/*36*/
SELECT * FROM CLIENTE
ORDER BY NOME_CLIENTE ASC; 
/*37*/
SELECT * FROM PRODUTO
ORDER BY VALOR_UNITARIO DESC;
/*38*/
SELECT * FROM VENDEDOR
ORDER BY SALARIO_FIXO DESC;
/*39*/
SELECT * FROM PEDIDO
ORDER BY PRAZO_ENTREGA_PEDIDO ASC;
/*40*/
SELECT * FROM PRODUTO
ORDER BY DESCRICAO_PRODUTO ASC, VALOR_UNITARIO DESC;
/*41*/
SELECT C.NOME_CLIENTE, COUNT(PE.NUM_PEDIDO) FROM CLIENTE C, PEDIDO PE
WHERE C.COD_CLIENTE = PE.COD_CLIENTE
GROUP BY NOME_CLIENTE;
/*42*/
SELECT V.NOME_VENDEDOR, COUNT(PE.NUM_PEDIDO) FROM VENDEDOR V, PEDIDO PE
WHERE V.COD_VENDEDOR = PE.COD_VENDEDOR
GROUP BY NOME_VENDEDOR;
/*43*/
SELECT P.NUM_PRODUTO, SUM(I.QUANT_PEDIDA) FROM PRODUTO P, ITEM_PEDIDO I
WHERE P.NUM_PRODUTO = I.NUM_PRODUTO
GROUP BY P.NUM_PRODUTO
ORDER BY P.NUM_PRODUTO ASC;
/*44*/
SELECT UNIDADE_PRODUTO, AVG(VALOR_UNITARIO) FROM PRODUTO
GROUP BY UNIDADE_PRODUTO;
/*45*/
SELECT NUM_PEDIDO, SUM(QUANT_PEDIDA) FROM ITEM_PEDIDO
GROUP BY NUM_PEDIDO
ORDER BY NUM_PEDIDO ASC;
/*46*/
SELECT UF_CLIENTE, COUNT(COD_CLIENTE) FROM CLIENTE
GROUP BY UF_CLIENTE;
/*47*/
SELECT P.NUM_PRODUTO, SUM(I.QUANT_PEDIDA*P.VALOR_UNITARIO) AS FATURAMENTO_TOTAL FROM ITEM_PEDIDO I, PRODUTO P
WHERE P.NUM_PRODUTO = I.NUM_PRODUTO
GROUP BY P.NUM_PRODUTO
ORDER BY P.NUM_PRODUTO ASC;
/*48*/
SELECT C.CID_CLIENTE, COUNT(P.NUM_PEDIDO) FROM CLIENTE C, PEDIDO P
WHERE C.COD_CLIENTE = P.COD_CLIENTE
GROUP BY C.CID_CLIENTE;
/*49*/
SELECT V.NOME_VENDEDOR, COUNT(PE.NUM_PEDIDO) FROM VENDEDOR V, PEDIDO PE
WHERE V.COD_VENDEDOR = PE.COD_VENDEDOR
GROUP BY NOME_VENDEDOR;
/*50*/
SELECT UNIDADE_PRODUTO, MAX(VALOR_UNITARIO) FROM PRODUTO
GROUP BY UNIDADE_PRODUTO;
/*51*/
SELECT PE.NUM_PEDIDO, C.NOME_CLIENTE FROM PEDIDO PE, CLIENTE C
WHERE C.COD_CLIENTE = PE.COD_CLIENTE;
/*52*/
SELECT PE.NUM_PEDIDO, V.NOME_VENDEDOR, PE.PRAZO_ENTREGA_PEDIDO FROM PEDIDO PE, VENDEDOR V
WHERE V.COD_VENDEDOR = PE.COD_VENDEDOR;
/*53*/
SELECT I.NUM_PEDIDO, P.DESCRICAO_PRODUTO, I.QUANT_PEDIDA FROM ITEM_PEDIDO I, PRODUTO P
WHERE P.NUM_PRODUTO = I.NUM_PRODUTO;
/*54*/
SELECT C.NOME_CLIENTE, PE.NUM_PEDIDO, V.NOME_VENDEDOR FROM PEDIDO PE, CLIENTE C, VENDEDOR V
WHERE C.COD_CLIENTE = PE.COD_CLIENTE AND V.COD_VENDEDOR = PE.COD_VENDEDOR;
/*55*/
SELECT C.NOME_CLIENTE, PE.NUM_PEDIDO, P.DESCRICAO_PRODUTO, I.QUANT_PEDIDA FROM PEDIDO PE, CLIENTE C, PRODUTO P, ITEM_PEDIDO I
WHERE C.COD_CLIENTE = PE.COD_CLIENTE AND PE.NUM_PEDIDO = I.NUM_PEDIDO AND P.NUM_PRODUTO = I.NUM_PRODUTO;
