/*01*/
SELECT COD_CLIENTE, NOME_CLIENTE FROM CLIENTE;
/*02*/
SELECT * FROM VENDEDOR WHERE SALARIO_FIXO > 3000.00;
/*03*/
SELECT DESCRICAO_PRODUTO, VALOR_UNITARIO FROM PRODUTO;
/*04*/
SELECT NUM_PEDIDO, PRAZO_ENTREGA_PEDIDO FROM PEDIDO;
/*05*/
SELECT NUM_PEDIDO, NOME_VENDEDOR FROM PEDIDO 
JOIN VENDEDOR ON VENDEDOR.COD_VENDEDOR = PEDIDO.COD_VENDEDOR;
/*06*/
SELECT NUM_PEDIDO, NOME_VENDEDOR, PRAZO_ENTREGA_PEDIDO FROM PEDIDO 
JOIN VENDEDOR ON VENDEDOR.COD_VENDEDOR = PEDIDO.COD_VENDEDOR;
/*07*/
SELECT * FROM PRODUTO WHERE VALOR_UNITARIO > 100;
/*08*/
SELECT NOME_CLIENTE FROM CLIENTE WHERE UF_CLIENTE = 'MG';
/*09*/
SELECT NUM_PEDIDO, PRAZO_ENTREGA_PEDIDO, PEDIDO.COD_CLIENTE, PEDIDO.COD_VENDEDOR, NOME_CLIENTE, NOME_VENDEDOR FROM PEDIDO 
JOIN VENDEDOR ON VENDEDOR.COD_VENDEDOR = PEDIDO.COD_VENDEDOR
JOIN CLIENTE ON CLIENTE.COD_CLIENTE = PEDIDO.COD_CLIENTE;
/*10*/
SELECT * FROM ITEM_PEDIDO;
/*11*/
SELECT NUM_PEDIDO, DESCRICAO_PRODUTO, QUANT_PEDIDA FROM ITEM_PEDIDO
JOIN PRODUTO ON PRODUTO.NUM_PRODUTO = ITEM_PEDIDO.NUM_PRODUTO;
/*12*/
SELECT * FROM CLIENTE C
WHERE C.COD_CLIENTE != ALL(SELECT COD_CLIENTE FROM PEDIDO);
/*13*/
SELECT * FROM VENDEDOR V
WHERE V.COD_VENDEDOR != ALL(SELECT COD_VENDEDOR FROM PEDIDO);
/*14*/
SELECT * FROM PRODUTO P
WHERE P.NUM_PRODUTO != ALL(SELECT NUM_PRODUTO FROM ITEM_PEDIDO);
/*15*/
SELECT NOME_CLIENTE, COUNT(NUM_PEDIDO) FROM CLIENTE C, PEDIDO P
WHERE C.COD_CLIENTE = P.COD_CLIENTE
GROUP BY NOME_CLIENTE;
/*16*/
SELECT NUM_PRODUTO, SUM(QUANT_PEDIDA) FROM ITEM_PEDIDO
GROUP BY NUM_PRODUTO;
/*17*/
SELECT AVG(VALOR_UNITARIO) FROM PRODUTO;
/*18*/
SELECT MAX(VALOR_UNITARIO), MIN(VALOR_UNITARIO)  FROM PRODUTO;
/*19*/
SELECT NOME_VENDEDOR, COUNT(NUM_PEDIDO) FROM VENDEDOR V, PEDIDO P
WHERE V.COD_VENDEDOR = P.COD_VENDEDOR
GROUP BY NOME_VENDEDOR;
/*20*/
SELECT * FROM CLIENTE
ORDER BY NOME_CLIENTE;
/*21*/
SELECT * FROM PRODUTO
ORDER BY VALOR_UNITARIO DESC;







