package com.graduacao.exercicios_3_3__4__5.gui;


import com.graduacao.exercicios_3_3__4__5.classes.Carro;
import com.graduacao.exercicios_3_3__4__5.gerenciadores.GerenciadorCarro;
import javax.swing.JOptionPane;


public class FrCadCarro extends javax.swing.JFrame {
    private boolean editando;
    private final GerenciadorCarro gerenciador;
    private String pathFile;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrCadCarro.class.getName());

    public FrCadCarro() {
        this.gerenciador = new GerenciadorCarro();
        initComponents();
        //this.pathFile = "listagens/exercicio04/ListagemCarros.csv";
        //this.pathFile = "listagens/exercicio04/ListagemCarros.xml";
        this.pathFile = "listagens/exercicio04/ListagemCarros.json";
        this.gerenciador.carregarDoArquivo(pathFile);
        this.edtListagem.setText(gerenciador.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        panCampos = new javax.swing.JPanel();
        lblCod = new javax.swing.JLabel();
        edtCod = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        edtMarca = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        edtPreco = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        edtModelo = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        edtAno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Carro");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        panBotoes.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        panBotoes.add(btnEditar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panBotoes.add(btnCancelar);

        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);
        panBotoes.add(btnExcluir);

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);
        panBotoes.add(btnSalvar);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);
        panBotoes.add(btnVoltar);

        panCampos.setBackground(new java.awt.Color(204, 204, 204));

        lblCod.setText("Código:");

        edtCod.setEnabled(false);

        lblMarca.setText("Marca:");

        edtMarca.setEnabled(false);

        lblPreco.setText("Preço:");

        edtPreco.setEnabled(false);

        lblModelo.setText("Modelo:");

        edtModelo.setEnabled(false);

        lblAno.setText("Ano:");

        edtAno.setEnabled(false);

        javax.swing.GroupLayout panCamposLayout = new javax.swing.GroupLayout(panCampos);
        panCampos.setLayout(panCamposLayout);
        panCamposLayout.setHorizontalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblCod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtModelo))
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panCamposLayout.setVerticalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(edtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(lblModelo)
                                .addComponent(edtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(lblMarca, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(lblCod))
                    .addComponent(edtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        edtListagem.setEditable(false);
        edtListagem.setColumns(20);
        edtListagem.setRows(5);
        jScrollPane1.setViewportView(edtListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panCampos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        FrExercicios_3_3__4__5.tela.setLocation(this.getLocation());
        this.setVisible(false);
        FrExercicios_3_3__4__5.tela.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.limparCampos();
        this.habilitarCampos(true);
        this.editando = false;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       Carro carro = this.camposParaObjeto();
       if(editando || !this.gerenciador.containsKey(carro.getCod())){
           this.gerenciador.put(carro);
       }else{
           JOptionPane.showMessageDialog(this, "Já existe um carro com este código!");
       }
       
       this.limparCampos();
       this.habilitarCampos(false);
       this.gerenciador.salvarNoArquivo(pathFile);
       this.edtListagem.setText(this.gerenciador.toString());
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       String cod = JOptionPane.showInputDialog(this, "Informe o código do carro", "");
       Carro carro = this.gerenciador.get(cod);
       
       if(carro != null){
           this.editando = true;
           this.limparCampos();
           this.habilitarCampos(true);
           this.edtCod.setEnabled(false);
           this.objetoParaCampos(carro);
       }else if(!cod.isEmpty()){
           JOptionPane.showMessageDialog(this, "Carro inexistente!");
       }
        
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String cod = JOptionPane.showInputDialog(this, "Informe o código do carro", "");
        Carro carro = this.gerenciador.remove(cod);
        if(carro == null){
            JOptionPane.showMessageDialog(this, "Carro inexistente!");
        }else if(!cod.isEmpty()){
            JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso!");
        }
        this.habilitarCampos(false);
        this.gerenciador.salvarNoArquivo(pathFile);
        this.edtListagem.setText(this.gerenciador.toString());
    }//GEN-LAST:event_btnExcluirActionPerformed
    public void habilitarCampos(boolean flag){
        this.edtCod.setEnabled(flag);
        this.edtMarca.setEnabled(flag);
        this.edtModelo.setEnabled(flag);
        this.edtPreco.setEnabled(flag);
        this.edtAno.setEnabled(flag);
        
        this.habilitarBotoes(flag);
    }
    
    public void habilitarBotoes(boolean flag){
        this.btnNovo.setEnabled(!flag);
        this.btnEditar.setEnabled(this.gerenciador.size() > 0 && !flag);
        this.btnCancelar.setEnabled(flag);
        this.btnExcluir.setEnabled(this.gerenciador.size() > 0 && !flag);
        this.btnSalvar.setEnabled(flag);
    }
    
    public void limparCampos(){
        this.edtCod.setText("");
        this.edtMarca.setText("");
        this.edtModelo.setText("");
        this.edtPreco.setText("");
        this.edtAno.setText("");
    }
    
    public Carro camposParaObjeto(){
        Carro carro = new Carro();
        carro.setCod(this.edtCod.getText());
        carro.setMarca(this.edtMarca.getText());
        carro.setModelo(this.edtModelo.getText());

        String precoStr = this.edtPreco.getText();
        if(!precoStr.isEmpty()){
            double preco = Double.parseDouble(precoStr);
            carro.setPreco(preco);
        }
        String anoStr = this.edtAno.getText();
        if(!anoStr.isEmpty()){
            int ano = Integer.parseInt(anoStr);
            carro.setAno(ano);
        }
        
        
        return carro;
    }
    
    public void objetoParaCampos(Carro carro){
        this.edtCod.setText(carro.getCod());
        this.edtMarca.setText(carro.getMarca());
        this.edtModelo.setText(carro.getModelo());
        this.edtPreco.setText(carro.getPreco()+"");
        this.edtAno.setText(carro.getAno()+"");
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField edtAno;
    private javax.swing.JTextField edtCod;
    private javax.swing.JTextArea edtListagem;
    private javax.swing.JTextField edtMarca;
    private javax.swing.JTextField edtModelo;
    private javax.swing.JTextField edtPreco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panBotoes;
    private javax.swing.JPanel panCampos;
    // End of variables declaration//GEN-END:variables
}
