
package com.graduacao.trabalhofinal.view;

import com.graduacao.trabalhofinal.connection.SQLiteConnector;
import com.graduacao.trabalhofinal.controller.AlbumController;
import com.graduacao.trabalhofinal.controller.ArtistaController;
import com.graduacao.trabalhofinal.controller.MusicaController;
import com.graduacao.trabalhofinal.model.dao.AlbumDAOBanco;
import com.graduacao.trabalhofinal.model.dao.ArtistaDAOBanco;
import com.graduacao.trabalhofinal.model.dao.IDAOAlbum;
import com.graduacao.trabalhofinal.model.dao.IDAOArtista;
import com.graduacao.trabalhofinal.model.dao.IDAOMusica;
import com.graduacao.trabalhofinal.model.dao.MusicaDAOBanco;
import com.graduacao.trabalhofinal.view.dialogs.DlgCadArtista;
import com.graduacao.trabalhofinal.view.dialogs.DlgCadMusica;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


public class FrHome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrHome.class.getName());
    
    private MusicaController musicaController;
    private AlbumController albumController;
    private ArtistaController artistaControler;
    /**
     * Creates new form FrTrabalhoFinal
     */
    public FrHome() {
        initComponents();
        try{
            /*
            ISerializadorMusica serializadorMusica = new SerializadorJSONMUsica();
            ISerializadorAlbum serializadorAlbum = new SerializadorJSONAlbum();
            ISerializadorArtista serializadorArtista = new SerializadorJSONArtista();
            IDAOMusica daoMusica = new MusicaDAOFile(serializadorMusica);
            IDAOAlbum daoAlbum = new AlbumDAOFile(serializadorAlbum);
            IDAOArtista daoArtista = new ArtistaDAOFile(serializadorArtista);
            */
            
            SQLiteConnector conexao = new SQLiteConnector("banco.sqlite");
            IDAOMusica daoMusica = new MusicaDAOBanco(conexao.getConnection());
            IDAOAlbum daoAlbum = new AlbumDAOBanco(conexao.getConnection());
            IDAOArtista daoArtista = new ArtistaDAOBanco(conexao.getConnection());
            this.musicaController = new MusicaController(daoMusica);
            this.albumController = new AlbumController(daoAlbum);
            this.artistaControler = new ArtistaController(daoArtista);
        }catch(SQLException e){
            logger.log(Level.SEVERE, e.getMessage(), e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panBotoes = new javax.swing.JPanel();
        btnMusica = new javax.swing.JButton();
        btnAlbum = new javax.swing.JButton();
        btnArtista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gerenciamento de Músicas");

        panBotoes.setBackground(new java.awt.Color(204, 204, 204));

        btnMusica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMusica.setText("Músicas");
        btnMusica.addActionListener(this::btnMusicaActionPerformed);
        panBotoes.add(btnMusica);

        btnAlbum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAlbum.setText("Álbuns");
        panBotoes.add(btnAlbum);

        btnArtista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnArtista.setText("Artistas");
        btnArtista.addActionListener(this::btnArtistaActionPerformed);
        panBotoes.add(btnArtista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicaActionPerformed
        DlgCadMusica cadMusica = new DlgCadMusica(this, true);
        cadMusica.setLocation(this.getLocation());
        cadMusica.setVisible(true);
    }//GEN-LAST:event_btnMusicaActionPerformed

    private void btnArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtistaActionPerformed
        DlgCadArtista cadArtista = new DlgCadArtista(this, true);
        cadArtista.setLocation(this.getLocation());
        cadArtista.setVisible(true);
    }//GEN-LAST:event_btnArtistaActionPerformed

    public MusicaController getMusicaController() {
        return this.musicaController;
    }

    public AlbumController getAlbumController() {
        return this.albumController;
    }

    public ArtistaController getArtistaControler() {
        return this.artistaControler;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlbum;
    private javax.swing.JButton btnArtista;
    private javax.swing.JButton btnMusica;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panBotoes;
    // End of variables declaration//GEN-END:variables
}
