package com.graduacao.exercicios_3_2.gui;

import com.graduacao.exercicios_3_2.classes.exercicio03.Casa;
import com.graduacao.exercicios_3_2.gerenciadores.exercicio03.GerenciadorCasa;
import javax.swing.JOptionPane;


public class FrCadCasa extends javax.swing.JFrame {
    private boolean editando;
    private final GerenciadorCasa gerenciador;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrCadCasa.class.getName());

    public FrCadCasa() {
        this.gerenciador = new GerenciadorCasa();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        panCampos = new javax.swing.JPanel();
        lblEndereco = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        edtArea = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        edtPreco = new javax.swing.JTextField();
        lblNumQuartos = new javax.swing.JLabel();
        edtNumQuartos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Casa");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        panBotoes.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        panBotoes.add(btnEditar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panBotoes.add(btnCancelar);

        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);
        panBotoes.add(btnExcluir);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);
        panBotoes.add(btnSalvar);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);
        panBotoes.add(btnVoltar);

        panCampos.setBackground(new java.awt.Color(204, 204, 204));

        lblEndereco.setText("Endereço:");

        edtEndereco.setEnabled(false);

        lblArea.setText("Área: ");

        edtArea.setEnabled(false);

        lblPreco.setText("Preço:");

        edtPreco.setEnabled(false);

        lblNumQuartos.setText("Número de Quartos: ");

        edtNumQuartos.setEnabled(false);

        javax.swing.GroupLayout panCamposLayout = new javax.swing.GroupLayout(panCampos);
        panCampos.setLayout(panCamposLayout);
        panCamposLayout.setHorizontalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumQuartos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtNumQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtEndereco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        panCamposLayout.setVerticalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(edtArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblArea, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(lblEndereco))
                    .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPreco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumQuartos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtPreco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(edtNumQuartos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        edtListagem.setEditable(false);
        edtListagem.setColumns(20);
        edtListagem.setRows(5);
        jScrollPane1.setViewportView(edtListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panCampos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        FrExercicios_3_2.tela.setLocation(this.getLocation());
        this.setVisible(false);
        FrExercicios_3_2.tela.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.limparCampos();
        this.habilitarCampos(true);
        this.editando = false;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       Casa casa = this.camposParaObjeto();
       if(editando || !this.gerenciador.containsKey(casa.getEndereco())){
           this.gerenciador.put(casa);
       }else{
           JOptionPane.showMessageDialog(this, "Já existe uma casa com este endereço!");
       }
       
       this.limparCampos();
       this.habilitarCampos(false);
       this.edtListagem.setText(this.gerenciador.toString());
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       String endereco = JOptionPane.showInputDialog(this, "Informe o endereço da casa", "");
       Casa casa = this.gerenciador.get(endereco);
       
       if(casa != null){
           this.editando = true;
           this.limparCampos();
           this.habilitarCampos(true);
           this.edtEndereco.setEnabled(false);
           this.objetoParaCampos(casa);
       }else if(!endereco.isEmpty()){
           JOptionPane.showMessageDialog(this, "Casa inexistente!");
       }
        
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String endereco = JOptionPane.showInputDialog(this, "Informe o endereço da casa", "");
        Casa casa = this.gerenciador.remove(endereco);
        if(casa == null){
            JOptionPane.showMessageDialog(this, "Casa inexistente!");
        }else if(!endereco.isEmpty()){
            JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso!");
        }
        this.edtListagem.setText(this.gerenciador.toString());
    }//GEN-LAST:event_btnExcluirActionPerformed
    public void habilitarCampos(boolean flag){
        this.edtEndereco.setEnabled(flag);
        this.edtArea.setEnabled(flag);
        this.edtPreco.setEnabled(flag);
        this.edtNumQuartos.setEnabled(flag);
    }
    
    public void limparCampos(){
        this.edtEndereco.setText("");
        this.edtArea.setText("");
        this.edtPreco.setText("");
        this.edtNumQuartos.setText("");
    }
    
    public Casa camposParaObjeto(){
        Casa casa = new Casa();
        casa.setEndereco(this.edtEndereco.getText());
        
        String areaStr = this.edtArea.getText();
        if(!areaStr.isEmpty()){
            double area = Double.parseDouble(areaStr);
            casa.setArea(area);
        }
        
        String precoStr = this.edtPreco.getText();
        if(!precoStr.isEmpty()){
            double preco = Double.parseDouble(precoStr);
            casa.setPreco(preco);
        }
        
        String numQuartosStr = this.edtNumQuartos.getText();
        if(!numQuartosStr.isEmpty()){
            int numQuartos = Integer.parseInt(numQuartosStr);
            casa.setNumQuartos(numQuartos);
        }
        
        return casa;
    }
    
    public void objetoParaCampos(Casa casa){
        this.edtEndereco.setText(casa.getEndereco());
        this.edtArea.setText(casa.getArea()+"");
        this.edtPreco.setText(casa.getPreco()+"");
        this.edtNumQuartos.setText(casa.getNumQuartos()+"");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField edtArea;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextArea edtListagem;
    private javax.swing.JTextField edtNumQuartos;
    private javax.swing.JTextField edtPreco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNumQuartos;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panBotoes;
    private javax.swing.JPanel panCampos;
    // End of variables declaration//GEN-END:variables
}
