
package com.graduacao.exercicios_3_2.gui;


public class FrExercicios_3_2 extends javax.swing.JFrame {
    
    public static FrExercicios_3_2 tela;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrExercicios_3_2.class.getName());

    /**
     * Creates new form FrExercicios_3_2
     */
    public FrExercicios_3_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panExercicios3_2 = new javax.swing.JPanel();
        btnExercicio01 = new javax.swing.JButton();
        btnExercicio02 = new javax.swing.JButton();
        btnExercicio03 = new javax.swing.JButton();
        btnExercicio04 = new javax.swing.JButton();
        btnExercicio05 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Exercícios 3.2");
        lblTitulo.setToolTipText("");
        lblTitulo.setOpaque(true);

        panExercicios3_2.setBackground(new java.awt.Color(204, 204, 204));
        panExercicios3_2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnExercicio01.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExercicio01.setText("Exercício01");
        btnExercicio01.setMaximumSize(new java.awt.Dimension(89, 23));
        btnExercicio01.addActionListener(this::btnExercicio01ActionPerformed);
        panExercicios3_2.add(btnExercicio01);

        btnExercicio02.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExercicio02.setText("Exercício02");
        btnExercicio02.setMaximumSize(new java.awt.Dimension(89, 23));
        btnExercicio02.addActionListener(this::btnExercicio02ActionPerformed);
        panExercicios3_2.add(btnExercicio02);

        btnExercicio03.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExercicio03.setText("Exercício03");
        btnExercicio03.setMaximumSize(new java.awt.Dimension(89, 23));
        btnExercicio03.addActionListener(this::btnExercicio03ActionPerformed);
        panExercicios3_2.add(btnExercicio03);

        btnExercicio04.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExercicio04.setText("Exercício04");
        btnExercicio04.setMaximumSize(new java.awt.Dimension(89, 23));
        panExercicios3_2.add(btnExercicio04);

        btnExercicio05.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExercicio05.setText("Exercício05");
        btnExercicio05.setMaximumSize(new java.awt.Dimension(89, 23));
        btnExercicio05.addActionListener(this::btnExercicio05ActionPerformed);
        panExercicios3_2.add(btnExercicio05);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panExercicios3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panExercicios3_2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExercicio01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExercicio01ActionPerformed
        this.setVisible(false);
        FrCadPessoa exercicio01Tela = new FrCadPessoa();
        exercicio01Tela.setLocation(this.getLocation());
        exercicio01Tela.setVisible(true);
    }//GEN-LAST:event_btnExercicio01ActionPerformed

    private void btnExercicio02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExercicio02ActionPerformed
        this.setVisible(false);
        FrCadProfessor exercicio02Tela = new FrCadProfessor();
        exercicio02Tela.setLocation(this.getLocation());
        exercicio02Tela.setVisible(true);
    }//GEN-LAST:event_btnExercicio02ActionPerformed

    private void btnExercicio03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExercicio03ActionPerformed
        this.setVisible(false);
        FrCadCasa exercicio03Tela = new FrCadCasa();
        exercicio03Tela.setLocation(this.getLocation());
        exercicio03Tela.setVisible(true);
    }//GEN-LAST:event_btnExercicio03ActionPerformed

    private void btnExercicio05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExercicio05ActionPerformed
        this.setVisible(false);
        FrCadAnimal exercicio05Tela = new FrCadAnimal();
        exercicio05Tela.setLocation(this.getLocation());
        exercicio05Tela.setVisible(true);
    }//GEN-LAST:event_btnExercicio05ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExercicio01;
    private javax.swing.JButton btnExercicio02;
    private javax.swing.JButton btnExercicio03;
    private javax.swing.JButton btnExercicio04;
    private javax.swing.JButton btnExercicio05;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panExercicios3_2;
    // End of variables declaration//GEN-END:variables
}
