
CREATE TABLE PESSOA(P_ID INT PRIMARY KEY,
	NOME VARCHAR(40) NOT NULL
);

CREATE TABLE ESTUDANTE(P_ID INT PRIMARY KEY,
	ID_DEPTO INT,
	STATUS VARCHAR(10),
	CONSTRAINT ID_ESTUDANTE FOREIGN KEY (P_ID) REFERENCES PESSOA (P_ID) ON DELETE CASCADE
);

CREATE TABLE DEPARTAMENTO(ID_DEPTO INT PRIMARY KEY,
	NOME_DEPTO VARCHAR(40) NOT NULL,
	P_ID INT
);

CREATE TABLE PROFESSOR(P_ID INT PRIMARY KEY,
	ID_DEPTO INT,
	TITULACAO VARCHAR(10),
	CONSTRAINT ID_PROFESSOR FOREIGN KEY (P_ID) REFERENCES PESSOA (P_ID) ON DELETE CASCADE,
	CONSTRAINT ID_DEPARTAMENTO FOREIGN KEY (ID_DEPTO) REFERENCES DEPARTAMENTO (ID_DEPTO) ON DELETE CASCADE
);

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT ID_CHEFIA FOREIGN KEY (P_ID) REFERENCES PROFESSOR(P_ID) ON DELETE SET NULL;

CREATE TABLE GRUPO_ESTUDOS (GE_ID INT PRIMARY KEY,
	NOME_GE VARCHAR(20) NOT NULL,
	LOCAL_GE VARCHAR(20) NOT NULL,
	P_ID INT,
	CONSTRAINT ID_PROFESSOR FOREIGN KEY (P_ID) REFERENCES PROFESSOR (P_ID) ON DELETE SET NULL
);

CREATE TABLE MEMBRO_GE (
	P_ID INT,
	GE_ID INT,
	CONSTRAINT ID_ESTUDANTE FOREIGN KEY (P_ID) REFERENCES ESTUDANTE (P_ID) ON DELETE CASCADE,
	CONSTRAINT ID_GRUPO FOREIGN KEY (GE_ID) REFERENCES GRUPO_ESTUDOS (GE_ID) ON DELETE CASCADE
);

ALTER TABLE MEMBRO_GE ADD CONSTRAINT CHAVES PRIMARY KEY (P_ID, GE_ID);

ALTER TABLE ESTUDANTE ADD CONSTRAINT ID_DEPARTAMENTO FOREIGN KEY (ID_DEPTO) REFERENCES DEPARTAMENTO (ID_DEPTO) ON DELETE CASCADE;



