/*
CREATE TABLE PESSOA(P_ID INT PRIMARY KEY,
	NOME VARCHAR(40) NOT NULL
);

CREATE TABLE ESTUDANTE(P_ID INT PRIMARY KEY,
	ID_DEPTO INT,
	STATUS VARCHAR(10),
	CONSTRAINT ID_ESTUDANTE FOREIGN KEY (P_ID) REFERENCES PESSOA (P_ID) ON DELETE CASCADE
);

CREATE TABLE DEPARTAMENTO(ID_DEPTO INT PRIMARY KEY,
	NOME_DEPTO VARCHAR(40) NOT NULL,
	P_ID INT
);

CREATE TABLE PROFESSOR(P_ID INT PRIMARY KEY,
	ID_DEPTO INT,
	TITULACAO VARCHAR(10),
	CONSTRAINT ID_PROFESSOR FOREIGN KEY (P_ID) REFERENCES PESSOA (P_ID) ON DELETE CASCADE,
	CONSTRAINT ID_DEPARTAMENTO FOREIGN KEY (ID_DEPTO) REFERENCES DEPARTAMENTO (ID_DEPTO) ON DELETE CASCADE
);

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT ID_CHEFIA FOREIGN KEY (P_ID) REFERENCES PROFESSOR(P_ID) ON DELETE SET NULL;

CREATE TABLE GRUPO_ESTUDOS (GE_ID INT PRIMARY KEY,
	NOME_GE VARCHAR(20) NOT NULL,
	LOCAL_GE VARCHAR(20) NOT NULL,
	P_ID INT,
	CONSTRAINT ID_PROFESSOR FOREIGN KEY (P_ID) REFERENCES PROFESSOR (P_ID) ON DELETE SET NULL
);

CREATE TABLE MEMBRO_GE (
	P_ID INT,
	GE_ID INT,
	CONSTRAINT ID_ESTUDANTE FOREIGN KEY (P_ID) REFERENCES ESTUDANTE (P_ID) ON DELETE CASCADE,
	CONSTRAINT ID_GRUPO FOREIGN KEY (GE_ID) REFERENCES GRUPO_ESTUDOS (GE_ID) ON DELETE CASCADE
);

ALTER TABLE MEMBRO_GE ADD CONSTRAINT CHAVES PRIMARY KEY (P_ID, GE_ID);

ALTER TABLE ESTUDANTE ADD CONSTRAINT ID_DEPARTAMENTO FOREIGN KEY (ID_DEPTO) REFERENCES DEPARTAMENTO (ID_DEPTO) ON DELETE CASCADE;
*/

/*
INSERT INTO PESSOA VALUES (413, 'John'), (1225, 'Dess'), (612, 'João'), (421, 'José'), (243, 'Pedro');
INSERT INTO PESSOA VALUES (1111, 'Joana'), (1025, 'Maria'), (123, 'Ruan'), (563, 'Paulo'), (122, 'Nathan');

INSERT INTO DEPARTAMENTO VALUES (321, 'Departamento de Ciência da Computação', NULL), 
								(125, 'Departamento de Ciências Agrárias', NULL),
								(512, 'Departamento de Ciências Exatas', NULL);
INSERT INTO PROFESSOR VALUES (1111, 321, 'Mestre'),
							 (1025, 125, 'Doutor'),
							 (123, 512, 'Doutor'),
							 (563, 321, 'Graduado'),
							 (122, 512, 'Graduado');
UPDATE DEPARTAMENTO SET P_ID = 1111 WHERE ID_DEPTO = 321;
UPDATE DEPARTAMENTO SET P_ID = 1025 WHERE ID_DEPTO = 125;
UPDATE DEPARTAMENTO SET P_ID = 123 WHERE ID_DEPTO = 512;

INSERT INTO ESTUDANTE VALUES (413, 321, 'ATIVO'),
							 (1225, 321, 'ATIVO'),
							 (612, 125, 'ATIVO'),
							 (421, 512, 'ATIVO'),
							 (243, 125, 'ATIVO');

INSERT INTO GRUPO_ESTUDOS VALUES (13, 'Jogos', 'Lab 06', 1111),
								 (14, 'Computação Gráfica', 'Lab 03', 123);

INSERT INTO MEMBRO_GE VALUES (413, 13), (1225, 13), (413, 14), (1225, 14), (612, 14);
*/

CREATE TABLE LOG_ESTUDANTE (
	OPERACAO CHAR(1) NOT NULL,
	HORARIO TIMESTAMP NOT NULL,
	ID_USUARIO TEXT NOT NULL,
	ID_ESTUDANTE INT NOT NULL,
	ID_DEPARTAMENTO INT NOT NULL,
	STATUS_ANTIGO VARCHAR(10) NOT NULL,
	STATUS_NOVO VARCHAR(10)
	

)

CREATE OR REPLACE FUNCTION

CREATE TRIGGER



