package com.graduacao.trabalhofinal.view.components;

import com.graduacao.trabalhofinal.model.entities.Musica;
import com.graduacao.trabalhofinal.view.tableModel.TMMusica;
import java.util.List;


public class PanTabelaMusica extends javax.swing.JPanel {

    public PanTabelaMusica() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        grdMusica = new javax.swing.JTable();

        grdMusica.setAutoCreateRowSorter(true);
        grdMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdMusicaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grdMusica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void grdMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdMusicaMouseClicked
        this.firePropertyChange("Linha Selecionada", false, true);
    }//GEN-LAST:event_grdMusicaMouseClicked
    
    public void atualizarTabela(List<Musica> musicas){
        TMMusica tmMusica = new TMMusica(musicas);
        this.grdMusica.setModel(tmMusica);
    }
    public Musica getSelectedRow(){
        Musica musica;
        TMMusica tmMusica = (TMMusica) grdMusica.getModel();
        musica = tmMusica.getRow(grdMusica.getSelectedRow());
        return musica;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable grdMusica;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
