package com.graduacao.trabalhofinal.view.components;

import com.graduacao.trabalhofinal.model.entities.Artista;
import com.graduacao.trabalhofinal.view.tableModel.TMArtista;
import java.util.List;
import javax.swing.RowSorter;


public class PanTabelaArtista extends javax.swing.JPanel {

    public PanTabelaArtista() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        grdArtista = new javax.swing.JTable();

        grdArtista.setShowGrid(true);
        grdArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdArtistaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grdArtista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void grdArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdArtistaMouseClicked
        this.firePropertyChange("Linha Selecionada", false, true);
    }//GEN-LAST:event_grdArtistaMouseClicked
    
    public void atualizarTabela(List<Artista> artistas){
        TMArtista tmArtista = new TMArtista(artistas);
        this.grdArtista.setModel(tmArtista);
    }
    
    public Artista getSelectedRow(){
        Artista artista;
        TMArtista tmArtista = (TMArtista) grdArtista.getModel();
        artista = tmArtista.getRow(grdArtista.getSelectedRow());
        return artista;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable grdArtista;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
