package com.graduacao.trabalhofinal.view.components;


import com.graduacao.trabalhofinal.model.entities.Album;
import com.graduacao.trabalhofinal.view.tableModel.TMAlbum;
import java.util.List;


public class PanTabelaAlbum extends javax.swing.JPanel {

    public PanTabelaAlbum() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        grdAlbum = new javax.swing.JTable();

        grdAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdAlbumMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grdAlbum);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void grdAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdAlbumMouseClicked
        this.firePropertyChange("Linha Selecionada", false, true);
    }//GEN-LAST:event_grdAlbumMouseClicked
    
    public void atualizarTabela(List<Album> albuns){
        TMAlbum tmAlbum = new TMAlbum(albuns);
        this.grdAlbum.setModel(tmAlbum);
    }
    
    public Album getSelectedRow(){
        Album album;
        TMAlbum tmAlbum = (TMAlbum) grdAlbum.getModel();
        album = tmAlbum.getRow(grdAlbum.getSelectedRow());
        return album;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable grdAlbum;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
