package com.graduacao.trabalhofinal.view.dialogs;

import com.graduacao.trabalhofinal.model.entities.Artista;
import com.graduacao.trabalhofinal.view.FrHome;
import java.util.logging.Level;


public class DlgArtistas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgArtistas.class.getName());
    private FrHome pai;
    private Artista artistaEscolhido;

    public DlgArtistas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.pai = (FrHome) parent;
        try{
            this.panTabelaArtista.atualizarTabela(this.pai.getArtistaControler().findAll());
        }catch(Exception e){
            logger.log(Level.SEVERE, e.getMessage(), e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEscolha = new javax.swing.JButton();
        panTabelaArtista = new com.graduacao.trabalhofinal.view.components.PanTabelaArtista();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Escolha um Artista");

        btnEscolha.setText("Escolher");
        btnEscolha.setEnabled(false);
        btnEscolha.addActionListener(this::btnEscolhaActionPerformed);
        jPanel1.add(btnEscolha);

        panTabelaArtista.addPropertyChangeListener(this::panTabelaArtistaPropertyChange);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panTabelaArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panTabelaArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolhaActionPerformed
        this.artistaEscolhido = this.panTabelaArtista.getSelectedRow();
        this.dispose();
    }//GEN-LAST:event_btnEscolhaActionPerformed

    private void panTabelaArtistaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_panTabelaArtistaPropertyChange
        this.btnEscolha.setEnabled(evt.getPropertyName().equals("Linha Selecionada"));
    }//GEN-LAST:event_panTabelaArtistaPropertyChange
    
    public Artista getArtistaEscolhido(){
        return this.artistaEscolhido;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscolha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    private com.graduacao.trabalhofinal.view.components.PanTabelaArtista panTabelaArtista;
    // End of variables declaration//GEN-END:variables
}
