package com.graduacao.trabalhofinal.view.dialogs;

import com.graduacao.trabalhofinal.controller.ArtistaController;
import com.graduacao.trabalhofinal.model.entities.Artista;
import com.graduacao.trabalhofinal.view.FrHome;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;


public class DlgCadArtista extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgCadArtista.class.getName());
    private boolean editando;
    private FrHome pai;
    private ArtistaController artistaController;

    public DlgCadArtista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.editando = false;
        this.pai = (FrHome) parent;
        this.artistaController = pai.getArtistaControler();
        try{
            this.atualizarTabela();
        }catch(Exception e){
            logger.log(Level.SEVERE, e.getMessage(), e);
        }
        this.habilitarCampos(false);
    }
    public void limparCampos(){
        this.edtCod.setText("");
        this.edtNome.setText("");
    }
    
    public void habilitarCampos(boolean flag){
        this.edtCod.setEnabled(flag && !editando);
        this.edtNome.setEnabled(flag);
        this.habilitarBotoes(flag);
    }
    public void habilitarBotoes(boolean flag){
        this.btnNovo.setEnabled(!flag);
        this.btnCancelar.setEnabled(flag);
        this.btnEditar.setEnabled(false);
        this.btnExcluir.setEnabled(false);
        this.btnSalvar.setEnabled(flag);
        this.btnAlbuns.setEnabled(false);
    }
    public void objetoParaCampos(Artista artista){
        this.edtCod.setText(artista.getCodArtista());
        this.edtNome.setText(artista.getNome());
    }
    public void atualizarTabela() throws Exception{
        this.panTabelaArtista.atualizarTabela(this.artistaController.findAll());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlbuns = new javax.swing.JButton();
        panCampos = new javax.swing.JPanel();
        lblCod = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        edtCod = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        panTabelaArtista = new com.graduacao.trabalhofinal.view.components.PanTabelaArtista();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Artistas");

        btnNovo.setText("Novo");
        btnNovo.setEnabled(false);
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        panBotoes.add(btnNovo);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panBotoes.add(btnCancelar);

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        panBotoes.add(btnEditar);

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);
        panBotoes.add(btnExcluir);

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);
        panBotoes.add(btnSalvar);

        btnAlbuns.setText("Visualizar Álbuns");
        btnAlbuns.setEnabled(false);
        btnAlbuns.addActionListener(this::btnAlbunsActionPerformed);
        panBotoes.add(btnAlbuns);

        panCampos.setBackground(new java.awt.Color(204, 204, 204));

        lblCod.setText("Código:");

        lblNome.setText("Nome: ");

        edtCod.setEnabled(false);

        edtNome.setEnabled(false);

        javax.swing.GroupLayout panCamposLayout = new javax.swing.GroupLayout(panCampos);
        panCampos.setLayout(panCamposLayout);
        panCamposLayout.setHorizontalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panCamposLayout.setVerticalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod)
                    .addComponent(edtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblNome)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panTabelaArtista.addPropertyChangeListener(this::panTabelaArtistaPropertyChange);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panTabelaArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panCampos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panTabelaArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panTabelaArtistaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_panTabelaArtistaPropertyChange
        if(evt.getPropertyName().equals("Linha Selecionada") && !this.btnSalvar.isEnabled()){
            this.btnEditar.setEnabled(true);
            this.btnExcluir.setEnabled(true);
            this.btnAlbuns.setEnabled(true);
        }
    }//GEN-LAST:event_panTabelaArtistaPropertyChange

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.limparCampos();
        this.editando = false;
        this.habilitarCampos(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Artista artista = this.panTabelaArtista.getSelectedRow();
        if(artista != null){
            this.limparCampos();
            this.editando = true;
            this.objetoParaCampos(artista);
            this.habilitarCampos(true);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Artista artista = this.panTabelaArtista.getSelectedRow();
        if(artista != null){
            try{
                this.artistaController.delete(artista.getCodArtista());
                List<String> codAlbuns = this.pai.getAlbumController().deleteByArtista(artista.getCodArtista());
                this.pai.getMusicaController().deleteByAlbuns(codAlbuns);
                this.atualizarTabela();
            }catch(Exception e){
                logger.log(Level.SEVERE, e.getMessage(), e);
            }
        }
        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try{
            if(this.editando){
                this.artistaController.update(this.edtCod.getText(), this.edtNome.getText());
                this.atualizarTabela();
            }else if(!this.artistaController.containsKey(this.edtCod.getText())){
                this.artistaController.save(this.edtCod.getText(), this.edtNome.getText());
                this.atualizarTabela();
            }else{
                JOptionPane.showMessageDialog(this, "Já existe um artista com este código!");
            }
        }catch(Exception e){
            logger.log(Level.SEVERE, e.getMessage(), e);
        }
        this.limparCampos();
        this.habilitarCampos(false);
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlbunsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlbunsActionPerformed
        Artista artista = this.panTabelaArtista.getSelectedRow();
        if(artista != null){
            DlgAlbuns albuns = new DlgAlbuns(this.pai, true, artista);
            albuns.setLocation(this.getLocation());
            albuns.setVisible(true);
        }
        
    }//GEN-LAST:event_btnAlbunsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlbuns;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtCod;
    private javax.swing.JTextField edtNome;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panBotoes;
    private javax.swing.JPanel panCampos;
    private com.graduacao.trabalhofinal.view.components.PanTabelaArtista panTabelaArtista;
    // End of variables declaration//GEN-END:variables
}
