package com.graduacao.trabalhofinal.view.dialogs;

import com.graduacao.trabalhofinal.controller.AlbumController;
import com.graduacao.trabalhofinal.model.entities.Album;
import com.graduacao.trabalhofinal.model.entities.Artista;
import com.graduacao.trabalhofinal.model.exceptions.ArtistaException;
import com.graduacao.trabalhofinal.view.FrHome;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;


public class DlgCadAlbum extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgCadAlbum.class.getName());
    private FrHome pai;
    private AlbumController albumController;
    private boolean editando;
    private Artista artistaAtual;
    public DlgCadAlbum(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.pai = (FrHome) parent;
        this.albumController = pai.getAlbumController();
        try{
            this.atualizarTabela();
        }catch(Exception e){
            logger.log(Level.SEVERE, e.getMessage(), e);
        }
        this.habilitarCampos(false);
    }
    
    public void habilitarCampos(boolean flag){
        this.edtCod.setEnabled(flag && !this.editando);
        this.edtNome.setEnabled(flag);
        this.edtAnoLancamento.setEnabled(flag);
        this.edtArtista.setVisible(flag & !editando);
        this.lblArtista.setVisible(flag && !editando);
        this.habilitarBotoes(flag);
    }
    public void habilitarBotoes(boolean flag){
        this.btnNovo.setEnabled(!flag);
        this.btnCancelar.setEnabled(flag);
        this.btnEditar.setEnabled(false);
        this.btnExcluir.setEnabled(false);
        this.btnSalvar.setEnabled(flag);
        this.btnMusicas.setEnabled(false);
        this.btnArtista.setVisible(flag && !editando);
    }
    public void limparCampos(){
        this.edtCod.setText("");
        this.edtNome.setText("");
        this.edtAnoLancamento.setText("");
    }
    public void objetoParaCampos(Album album){
        this.edtCod.setText(album.getCodAlbum());
        this.edtNome.setText(album.getNome());
        this.edtAnoLancamento.setText(album.getAnoLancamento() + "");
    }
    public void atualizarTabela()throws Exception{
        this.panTabelaAlbum.atualizarTabela(this.albumController.findAll());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnMusicas = new javax.swing.JButton();
        panCampos = new javax.swing.JPanel();
        lblCod = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblAnoLancamento = new javax.swing.JLabel();
        edtCod = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        edtAnoLancamento = new javax.swing.JTextField();
        btnArtista = new javax.swing.JButton();
        edtArtista = new javax.swing.JTextField();
        lblArtista = new javax.swing.JLabel();
        panTabelaAlbum = new com.graduacao.trabalhofinal.view.components.PanTabelaAlbum();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Álbuns");

        btnNovo.setText("Novo");
        btnNovo.setEnabled(false);
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        panBotoes.add(btnNovo);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panBotoes.add(btnCancelar);

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        panBotoes.add(btnEditar);

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);
        panBotoes.add(btnExcluir);

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);
        panBotoes.add(btnSalvar);

        btnMusicas.setText("Visualizar Músicas");
        btnMusicas.setEnabled(false);
        btnMusicas.addActionListener(this::btnMusicasActionPerformed);
        panBotoes.add(btnMusicas);

        panCampos.setBackground(new java.awt.Color(204, 204, 204));

        lblCod.setText("Código: ");

        lblNome.setText("Nome: ");

        lblAnoLancamento.setText("Ano de Lançamento: ");

        edtCod.setEnabled(false);

        edtNome.setEnabled(false);

        edtAnoLancamento.setEnabled(false);

        btnArtista.setText("Escolher Artista");
        btnArtista.addActionListener(this::btnArtistaActionPerformed);

        edtArtista.setEnabled(false);

        lblArtista.setText("Artista Escolhido: ");

        javax.swing.GroupLayout panCamposLayout = new javax.swing.GroupLayout(panCampos);
        panCampos.setLayout(panCamposLayout);
        panCamposLayout.setHorizontalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblCod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAnoLancamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtAnoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(btnArtista)
                        .addGap(3, 3, 3)
                        .addComponent(lblArtista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panCamposLayout.setVerticalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod)
                    .addComponent(edtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblNome)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblAnoLancamento)
                    .addComponent(edtAnoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArtista)
                    .addComponent(lblArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        panTabelaAlbum.addPropertyChangeListener(this::panTabelaAlbumPropertyChange);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panTabelaAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panTabelaAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.limparCampos();
        this.editando = false;
        this.habilitarCampos(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Album album = this.panTabelaAlbum.getSelectedRow();
        if(album != null){
            this.limparCampos();
            this.editando = true;
            this.objetoParaCampos(album);
            this.habilitarCampos(true);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Album album = this.panTabelaAlbum.getSelectedRow();
        if(album != null){
            try{
                this.albumController.delete(album.getCodAlbum());
                this.pai.getMusicaController().deleteByAlbum(album.getCodAlbum());
                this.atualizarTabela();
            }
            catch(Exception e){
                logger.log(Level.SEVERE, e.getMessage(), e);
            }
            
        }
        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try{
            if(this.editando){
                this.albumController.update(this.edtCod.getText(), this.edtNome.getText(), this.edtAnoLancamento.getText());
                this.atualizarTabela();
            }else if(this.artistaAtual == null){
                throw new ArtistaException("Error - Nenhum Artista Escolhido");
            }else if(!this.albumController.containsKey(this.edtCod.getText())){
                this.albumController.save(this.edtCod.getText(), this.edtNome.getText(), artistaAtual.getCodArtista(), this.edtAnoLancamento.getText());
                this.artistaAtual = null;
                this.edtArtista.setText("");
                this.atualizarTabela();
            }else{
                JOptionPane.showMessageDialog(this, "Já existe um Álbum com este código!");
            }
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(Exception e){
            logger.log(Level.SEVERE, e.getMessage(), e);
        }
        this.limparCampos();
        this.habilitarCampos(false);

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicasActionPerformed
        Album album = this.panTabelaAlbum.getSelectedRow();
        if(album != null){
            DlgMusicas albuns = new DlgMusicas(this.pai, true, album);
            albuns.setLocation(this.getLocation());
            albuns.setVisible(true);
        }

    }//GEN-LAST:event_btnMusicasActionPerformed

    private void btnArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtistaActionPerformed
        DlgArtistas artistas = new DlgArtistas(pai, true);
        artistas.setLocation(this.getLocation());
        artistas.setVisible(true);
        
        this.artistaAtual = artistas.getArtistaEscolhido();
        if(this.artistaAtual != null){
            this.edtArtista.setText(this.artistaAtual.getNome());
        }else{
            this.edtArtista.setText("");
        }
        
    }//GEN-LAST:event_btnArtistaActionPerformed

    private void panTabelaAlbumPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_panTabelaAlbumPropertyChange
        if(evt.getPropertyName().equals("Linha Selecionada") && !this.btnSalvar.isEnabled()){
            this.btnMusicas.setEnabled(true);
            this.btnEditar.setEnabled(true);
            this.btnExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_panTabelaAlbumPropertyChange



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArtista;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnMusicas;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtAnoLancamento;
    private javax.swing.JTextField edtArtista;
    private javax.swing.JTextField edtCod;
    private javax.swing.JTextField edtNome;
    private javax.swing.JLabel lblAnoLancamento;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panBotoes;
    private javax.swing.JPanel panCampos;
    private com.graduacao.trabalhofinal.view.components.PanTabelaAlbum panTabelaAlbum;
    // End of variables declaration//GEN-END:variables
}
