
package com.graduacao.roteiro04.gui;

import com.graduacao.roteiro04.gerentes.GerenteConsulta;
import com.graduacao.roteiro04.gerentes.GerenteMedico;
import com.graduacao.roteiro04.gerentes.GerentePaciente;




public class FrHome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrHome.class.getName());
    
    private final GerenteConsulta gerenteConsultas;
    private final GerenteMedico gerenteMedicos;
    private final GerentePaciente gerentePacientes;
    private String pathFileConsulta;
    private String pathFileMedico;
    private String pathFilePaciente;

    public FrHome() {
        initComponents();
        this.gerenteConsultas = new GerenteConsulta();
        this.gerenteMedicos = new GerenteMedico();
        this.gerentePacientes = new GerentePaciente();
        
        this.pathFileConsulta = "listagens/exercicio01/ListagemConsultas.json";
        this.pathFileMedico = "listagens/exercicio01/ListagemMedicos.json";
        this.pathFilePaciente = "listagens/exercicio01/ListagemPacientes.json";
        
       /* this.gerenteConsultas.carregarDoArquivo(this.pathFileConsulta);
        this.gerenteMedicos.carregarDoArquivo(this.pathFileMedico);
        this.gerentePacientes.carregarDoArquivo(this.pathFilePaciente);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panBotoes = new javax.swing.JPanel();
        btnConsultas = new javax.swing.JButton();
        btnCadPacientes = new javax.swing.JButton();
        btnCadMedicos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Agendamento de Consultas Médicas");

        panBotoes.setBackground(new java.awt.Color(204, 204, 204));

        btnConsultas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultas.setText("Consultas");
        btnConsultas.addActionListener(this::btnConsultasActionPerformed);
        panBotoes.add(btnConsultas);

        btnCadPacientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadPacientes.setText("Cadastro Pacientes");
        btnCadPacientes.addActionListener(this::btnCadPacientesActionPerformed);
        panBotoes.add(btnCadPacientes);

        btnCadMedicos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadMedicos.setText("Cadastro Médicos");
        btnCadMedicos.addActionListener(this::btnCadMedicosActionPerformed);
        panBotoes.add(btnCadMedicos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed

    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnCadPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacientesActionPerformed

    }//GEN-LAST:event_btnCadPacientesActionPerformed

    private void btnCadMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadMedicosActionPerformed

    }//GEN-LAST:event_btnCadMedicosActionPerformed

    public GerenteConsulta getGerenteConsultas() {
        return this.gerenteConsultas;
    }
     public GerenteMedico getGerenteMedicos() {
        return this.gerenteMedicos;
    }
    public GerentePaciente getGerentePacientes() {
        return this.gerentePacientes;
    }
    public String getPathFileConsulta() {
        return this.pathFileConsulta;
    }

    public String getPathFileMedico() {
        return this.pathFileMedico;
    }

    public String getPathFilePaciente() {
        return this.pathFilePaciente;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadMedicos;
    private javax.swing.JButton btnCadPacientes;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panBotoes;
    // End of variables declaration//GEN-END:variables
}
