package com.graduacao.exercicios_3_6.gui.exercicio01.dialogs;

import com.graduacao.exercicios_3_6.classes.exercicio01.Professor;
import com.graduacao.exercicios_3_6.gerentes.exercicio01.GerenteProfessor;
import com.graduacao.exercicios_3_6.gui.exercicio01.FrHomeEx01;
import javax.swing.JOptionPane;

public class DlgCadProfessor extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgCadProfessor.class.getName());
    
    private FrHomeEx01 pai;
    private final GerenteProfessor gerente;
    private boolean editando;
    private String pathFile;
    public DlgCadProfessor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        this.pai = (FrHomeEx01) parent;
        this.gerente = this.pai.getGerenteProfessores();
        this.pathFile = this.pai.getPathFileProfessor();
        this.edtListagem.setText(this.gerente.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        panCampos = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        edtCpf = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        edtSexo = new javax.swing.JTextField();
        lblIdade = new javax.swing.JLabel();
        edtIdade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Professores");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        panBotoes.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        panBotoes.add(btnEditar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panBotoes.add(btnCancelar);

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);
        panBotoes.add(btnExcluir);

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);
        panBotoes.add(btnSalvar);

        panCampos.setBackground(new java.awt.Color(204, 204, 204));

        lblCpf.setText("CPF: ");

        edtCpf.setEnabled(false);

        lblNome.setText("Nome: ");

        edtNome.setEnabled(false);

        lblSexo.setText("Sexo: ");

        edtSexo.setEnabled(false);

        lblIdade.setText("Idade: ");

        edtIdade.setEnabled(false);

        javax.swing.GroupLayout panCamposLayout = new javax.swing.GroupLayout(panCampos);
        panCampos.setLayout(panCamposLayout);
        panCamposLayout.setHorizontalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblCpf)
                        .addGap(6, 6, 6)
                        .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblIdade)
                        .addGap(6, 6, 6)
                        .addComponent(edtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panCamposLayout.setVerticalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCpf)
                    .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSexo)
                    .addComponent(edtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIdade)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        edtListagem.setEditable(false);
        edtListagem.setColumns(20);
        edtListagem.setRows(5);
        jScrollPane1.setViewportView(edtListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.editando = false;
        this.limparCampos();
        this.habilitarCampos(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        DlgEscolhaProfessor escolha = new DlgEscolhaProfessor(this.pai,true,this.gerente);
        escolha.setLocation(this.getLocation());
        escolha.setVisible(true);
        
        Professor professor = escolha.getProfessorEscolhido();
        if(professor != null){
            this.limparCampos();
            this.editando = true;
            this.habilitarCampos(true);
            this.objetoParaCampos(professor);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        DlgEscolhaProfessor escolha = new DlgEscolhaProfessor(this.pai,true,this.gerente);
        escolha.setLocation(this.getLocation());
        escolha.setVisible(true);
        
        Professor professor = this.gerente.remove(escolha.getProfessorEscolhido().getCpf());
        if(professor != null){
            JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso!");
        }
        this.habilitarCampos(false);
        this.edtListagem.setText(this.gerente.toString());
        this.gerente.salvarNoArquivo(pathFile);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Professor professor = this.camposParaObjeto();
        
        if(editando || !this.gerente.containsKey(professor.getCpf())){
            this.gerente.put(professor);
        }
        else{
            JOptionPane.showMessageDialog(this, "Já existe um professor com este Cpf!");
        }
        this.limparCampos();
        this.habilitarCampos(false);
        this.gerente.salvarNoArquivo(this.pathFile);
        this.edtListagem.setText(this.gerente.toString());
    }//GEN-LAST:event_btnSalvarActionPerformed

    public void habilitarCampos(boolean flag){
        this.edtCpf.setEnabled(!this.editando && flag);
        this.edtNome.setEnabled(flag);
        this.edtSexo.setEnabled(flag);
        this.edtIdade.setEnabled(flag);
        
        this.habilitarBotoes(flag);
    }
    public void habilitarBotoes(boolean flag){
        this.btnNovo.setEnabled(!flag);
        this.btnEditar.setEnabled(this.gerente.size() > 0 && !flag);
        this.btnCancelar.setEnabled(flag);
        this.btnExcluir.setEnabled(this.gerente.size() > 0 && !flag);
        this.btnSalvar.setEnabled(flag);
    }
    public void limparCampos(){
        this.edtCpf.setText("");
        this.edtNome.setText("");
        this.edtSexo.setText("");
        this.edtIdade.setText("");
    }
    
    public void objetoParaCampos(Professor professor){
        this.edtCpf.setText(professor.getCpf());
        this.edtNome.setText(professor.getNome());
        this.edtSexo.setText(professor.getSexo()+"");
        this.edtIdade.setText(professor.getIdade()+"");
    }
    public Professor camposParaObjeto(){
        Professor professor = new Professor();
        professor.setCpf(this.edtCpf.getText());
        professor.setNome(this.edtNome.getText());
        
        String sexoStr = this.edtSexo.getText();
        if(!sexoStr.isEmpty() && sexoStr.length() == 1){
            char sexo = sexoStr.charAt(0);
            professor.setSexo(sexo);
        }
        String idadeStr = this.edtIdade.getText();
        if(!idadeStr.isEmpty()){
            int idade = Integer.parseInt(idadeStr);
            professor.setIdade(idade);
        }
        
       return professor;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtCpf;
    private javax.swing.JTextField edtIdade;
    private javax.swing.JTextArea edtListagem;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtSexo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panBotoes;
    private javax.swing.JPanel panCampos;
    // End of variables declaration//GEN-END:variables
}
