
package com.graduacao.exercicios_3_6.gui.exercicio01.dialogs;

import com.graduacao.exercicios_3_6.classes.exercicio01.Aluno;
import com.graduacao.exercicios_3_6.classes.exercicio01.Disciplina;
import com.graduacao.exercicios_3_6.classes.exercicio01.Professor;
import com.graduacao.exercicios_3_6.gui.exercicio01.FrHomeEx01;
import javax.swing.JOptionPane;

public class DlgDisciplina extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgDisciplina.class.getName());
    private FrHomeEx01 pai;
    private Disciplina disciplina;
    private boolean pronto;
    
    public DlgDisciplina(java.awt.Frame parent, boolean modal, Disciplina disciplina, boolean editar) {
        super(parent, modal);
        initComponents();
        this.pronto = false;
        this.pai = (FrHomeEx01) parent;
        this.disciplina = disciplina;
        
        
        this.edtCodigo.setEnabled(!editar);
        this.atualizarDisciplina();
        this.habilitarBotao();
        this.objetoParaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo1 = new javax.swing.JLabel();
        panGerenciar = new javax.swing.JPanel();
        btnProfessor = new javax.swing.JButton();
        btnAddAluno = new javax.swing.JButton();
        btnRemoveAluno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtDisciplina = new javax.swing.JTextArea();
        panConfirmar = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        panCampos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblHorario = new javax.swing.JLabel();
        edtHorario = new javax.swing.JTextField();
        lblSemestre = new javax.swing.JLabel();
        edtSemestre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("Disciplina");

        panGerenciar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnProfessor.setText("Escolher Prof.");
        btnProfessor.addActionListener(this::btnProfessorActionPerformed);
        panGerenciar.add(btnProfessor);

        btnAddAluno.setText("Add Aluno");
        btnAddAluno.addActionListener(this::btnAddAlunoActionPerformed);
        panGerenciar.add(btnAddAluno);

        btnRemoveAluno.setText("Remover Aluno");
        btnRemoveAluno.addActionListener(this::btnRemoveAlunoActionPerformed);
        panGerenciar.add(btnRemoveAluno);

        edtDisciplina.setEditable(false);
        edtDisciplina.setColumns(20);
        edtDisciplina.setRows(5);
        jScrollPane1.setViewportView(edtDisciplina);

        panConfirmar.setBackground(new java.awt.Color(204, 204, 204));
        panConfirmar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panConfirmar.add(btnCancelar);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);
        panConfirmar.add(btnSalvar);

        panCampos.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Código: ");

        lblNome.setText("Nome: ");

        edtNome.setToolTipText("");

        lblHorario.setText("Horário: ");

        lblSemestre.setText("Semestre: ");

        edtSemestre.setToolTipText("");

        javax.swing.GroupLayout panCamposLayout = new javax.swing.GroupLayout(panCampos);
        panCampos.setLayout(panCamposLayout);
        panCamposLayout.setHorizontalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCamposLayout.createSequentialGroup()
                        .addComponent(lblHorario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSemestre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtSemestre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panCamposLayout.setVerticalGroup(
            panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNome))
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorario)
                    .addComponent(edtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSemestre)
                    .addComponent(edtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panGerenciar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(panGerenciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessorActionPerformed
        DlgEscolhaProfessor escolha = new DlgEscolhaProfessor(this.pai,true,this.pai.getGerenteProfessores());
        escolha.setLocation(this.getLocation());
        escolha.setVisible(true);
        
        Professor professor = escolha.getProfessorEscolhido();
        if(professor != null){
            this.disciplina.setMinistrante(professor);
            this.atualizarDisciplina();
        }
    }//GEN-LAST:event_btnProfessorActionPerformed

    private void btnAddAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAlunoActionPerformed
        DlgEscolhaAluno escolha = new DlgEscolhaAluno(this.pai,true,this.pai.getGerenteAlunos());
        escolha.setLocation(this.getLocation());
        escolha.setVisible(true);
        
        Aluno aluno = escolha.getAlunoEscolhido();
        if(aluno != null){
           this.disciplina.getGerenteAlunos().put(aluno);
           this.atualizarDisciplina();
           this.habilitarBotao();
        }
    }//GEN-LAST:event_btnAddAlunoActionPerformed

    private void btnRemoveAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAlunoActionPerformed

        DlgEscolhaAluno escolha = new DlgEscolhaAluno(this.pai,true,this.disciplina.getGerenteAlunos());
        escolha.setLocation(this.getLocation());
        escolha.setVisible(true);
        
        Aluno aluno = escolha.getAlunoEscolhido();
        if(aluno != null){
            this.disciplina.getGerenteAlunos().remove(aluno.getMatricula());
            JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso!");
            this.atualizarDisciplina();
            this.habilitarBotao();
        }
        
    }//GEN-LAST:event_btnRemoveAlunoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(!this.edtCodigo.getText().isBlank()){
            this.camposParaObjeto();
            this.pronto = true;
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Preencha o código!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    public void camposParaObjeto(){
        this.disciplina.setCod(this.edtCodigo.getText());
        this.disciplina.setNome(this.edtNome.getText());
        this.disciplina.setHorario(this.edtHorario.getText());
        
        String semestreStr = this.edtSemestre.getText();
        if(!semestreStr.isEmpty()){
            int semestre = Integer.parseInt(semestreStr);
            this.disciplina.setSemestre(semestre);
        }
    }
    
    public void objetoParaCampos(){
        this.edtCodigo.setText(this.disciplina.getCod());
        this.edtNome.setText(this.disciplina.getNome());
        this.edtHorario.setText(this.disciplina.getHorario());
        this.edtSemestre.setText(this.disciplina.getSemestre()+"");
    }
    
    public boolean isPronto() {
        return this.pronto;
    }
    public void habilitarBotao(){
        this.btnRemoveAluno.setEnabled(this.disciplina.getGerenteAlunos().size() > 0);
    }
    public void atualizarDisciplina(){
        this.edtDisciplina.setText(this.disciplina.getMinistrante().toString() + this.disciplina.getGerenteAlunos().toString());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAluno;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnProfessor;
    private javax.swing.JButton btnRemoveAluno;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextArea edtDisciplina;
    private javax.swing.JTextField edtHorario;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtSemestre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSemestre;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel panCampos;
    private javax.swing.JPanel panConfirmar;
    private javax.swing.JPanel panGerenciar;
    // End of variables declaration//GEN-END:variables
}
